import type { WordleLanguage } from "@/types/gameTypes";

// Zu erratende Wörter, exakt 5 Buchstaben, nur A-Z in Großbuchstaben.
//
// Bewusst OHNE Umlaute (ä/ö/ü) und ß, damit die Bildschirmtastatur mit einem
// einfachen A-Z-Layout auskommt und dieselbe Tastatur für beide Sprachen passt.
// Als "erlaubte Rateversuche" gilt jedes Wort dieser Liste; darüber hinaus wird
// nur die Länge geprüft (siehe utils.isAllowedGuess) - so werden auch seltene,
// hier nicht gelistete Wörter akzeptiert.
//
// Die Listen werden am Ende über `clean()` entdoppelt UND defensiv auf exakt
// fünf Buchstaben gefiltert: ein Tippfehler (z.B. 4- oder 6-Buchstaben-Wort)
// fällt so heraus, statt das Raster kaputtzumachen.

const DE: string[] = [
  "ABEND", "ADLER", "AMPEL", "APFEL", "ARENA", "ATLAS", "BADEN", "BIENE",
  "BIRNE", "BLATT", "BLUME", "BODEN", "BOGEN", "BRAUN", "BRIEF", "BRUCH",
  "BUCHT", "DACHS", "DAMPF", "DATEN", "DECKE", "DIEBE", "DONAU", "DRAHT",
  "EIMER", "EISEN", "ENGEL", "ERBSE", "ESSEN", "FADEN", "FALKE", "FARBE",
  "FEDER", "FISCH", "FLUSS", "FUCHS", "GABEL", "GEIGE", "GEIST", "GLANZ",
  "GLEIS", "GRUBE", "HAFEN", "HAKEN", "HALLO", "HANDY", "HASEN", "HAUCH",
  "HERDE", "HONIG", "HOTEL", "HUMOR", "INSEL", "JACKE", "JAHRE", "KABEL",
  "KAMEL", "KANAL", "KARTE", "KASSE", "KATZE", "KEGEL", "KERZE", "KETTE",
  "KIOSK", "KLANG", "KLEID", "KOALA", "KOMET", "KRAFT", "KRANZ", "KREIS",
  "KRONE", "KUGEL", "LAMPE", "LAUCH", "LEBEN", "LEDER", "LICHT", "LINIE",
  "LIPPE", "LOTSE", "MAGEN", "MALER", "MANGO", "METER", "MILCH", "MOTOR",
  "MUSIK", "NADEL", "NASEN", "NEBEL", "NELKE", "NIERE", "NUDEL", "ONKEL",
  "ORGEL", "OSTEN", "PALME", "PANDA", "PAUSE", "PFEIL", "PFERD", "PILOT",
  "PIZZA", "PLANE", "PLATZ", "PUDEL", "QUARK", "RASEN", "RATTE", "REGEN",
  "REISE", "RIESE", "ROBBE", "ROSEN", "RUDER", "SALAT", "SAMEN", "SCHAF",
  "SEGEL", "SEIFE", "SIRUP", "SONNE", "SPECK", "SPIEL", "STEIN", "STERN",
  "STROH", "TAFEL", "TASSE", "TAUBE", "TEICH", "TIGER", "TISCH", "TRAUM",
  "TULPE", "VOGEL", "WAGEN", "WANNE", "WESPE", "WOLKE", "WURST", "ZEBRA",
  "ZIEGE", "ZWERG",
  // Erweiterung
  "ACKER", "AGENT", "AKTEN", "ALARM", "ALIBI", "ALPEN", "AMSEL", "ANKER",
  "ASTER", "AUTOR", "BARON", "BEERE", "BEUTE", "BIBER", "BLECH", "BLICK",
  "BLITZ", "BLOCK", "BONUS", "BRAND", "DAMEN", "DANKE", "DATUM", "DELTA",
  "DEPOT", "DOSEN", "DRUCK", "DUELL", "DUNST", "EBENE", "EHREN", "EICHE",
  "EIFER", "ELCHE", "ELFEN", "ENTEN", "ERNTE", "EULEN", "FABEL", "FASAN",
  "FAUST", "FERNE", "FESTE", "FILME", "FIRMA", "FJORD", "FLIRT", "FLORA",
  "FLOTT", "FLUCH", "FONDS", "FORST", "FRONT", "FROST", "FUNKE", "GALLE",
  "GARBE", "GARDE", "GASSE", "GECKO", "GEIER", "GENIE", "GNOME", "GOLEM",
  "GRAMM", "GRAND", "GRIFF", "GROLL", "GRUND", "GURKE", "HABEN", "HAGEL",
  "HEBEL", "HECKE", "HEIDE", "HELIX", "HENNE", "HEXEN", "HIRTE", "HORDE",
  "HORST", "HOSEN", "IDEEN", "IMKER", "JOKER", "JUBEL", "JUWEL", "KADER",
  "KAKAO", "KAMIN", "KANTE", "KAPPE", "KARST", "KELCH", "KELLE", "KERBE",
  "KEULE", "KISTE", "KLAUE", "KLIMA", "KLUFT", "KNAPP", "KOBRA", "KOHLE",
  "KOMMA", "KONTO", "KOPIE", "KRAUT", "KREBS", "KURVE", "LACHS", "LADEN",
  "LAGER", "LAKEN", "LARVE", "LASER", "LASSO", "LATTE", "LAUNE", "LEHRE",
  "LEINE", "LEUTE", "LIANE", "LILIE", "LINDE", "LITER", "LOGIK", "LOTTO",
  "LUCHS", "MAFIA", "MAKEL", "MARKE", "MASSE", "MATTE", "MAUER", "MEISE",
  "MENGE", "MEUTE", "MINUS", "MITTE", "MODEM", "MOLKE", "MONAT", "MONDE",
  "MOPED", "MORAL", "MOTTE", "MULDE", "MUMIE", "NABEL", "NACHT", "NAGEL",
  "NARBE", "NEFFE", "NETTO", "NIETE", "NONNE", "NOTEN", "OASEN", "OBHUT",
  "OCHSE", "OFFEN", "OKAPI", "OPFER", "ORDEN", "OTTER", "PAKET", "PANIK",
  "PAPST", "PARKA", "PASTA", "PAUKE", "PEGEL", "PERLE", "PESTO", "PFAND",
  "PFLUG", "PFOTE", "PHASE", "PINIE", "PIRAT", "PISTE", "PIXEL", "POKAL",
  "POKER", "PRINZ", "PROBE", "PROSA", "PSALM", "PUDER", "PUMPE", "PUNKT",
  "PUPPE", "QUALM", "QUOTE", "RABEN", "RADAR", "RAPPE", "RAUCH", "RAUPE",
  "RAUTE", "REBUS", "RECHT", "REDEN", "REGAL", "REGEL", "REICH", "REVUE",
  "RHEIN", "RILLE", "RINDE", "RIPPE", "RODEO", "ROGEN", "ROLLE", "ROMAN",
  "RONDO", "ROTOR", "RUBIN", "RUINE", "RUMBA", "RUMPF", "RUNDE", "RUSSE",
  "SAHNE", "SAITE", "SALBE", "SALDO", "SALON", "SALVE", "SAMBA", "SATAN",
  "SAUNA", "SCHAL", "SCHUH", "SEELE", "SEHER", "SEHNE", "SEKTE", "SENAT",
  "SERIE", "SESAM", "SICHT", "SIEBE", "SIEGE", "SILBE", "SILOS", "SKALA",
  "SOCKE", "SOHLE", "SORTE", "SOSSE", "SPALT", "SPATZ", "SPORE", "SPORN",
  "SPRAY", "SPULE", "STAAT", "STAMM", "STAND", "STAUB", "STELE", "STICH",
  "STIEL", "STIER", "STIFT", "STOFF", "STOLZ", "STUBE", "STUFE", "STUMM",
  "STUTE", "STURM", "SUITE", "SUMPF", "SUPPE", "SUSHI", "TABAK", "TADEL",
  "TALER", "TANGO", "TANTE", "TAPIR", "TAROT", "TASTE", "TATZE", "THEKE",
  "THRON", "TINTE", "TITAN", "TITEL", "TONER", "TONNE", "TOPAS", "TORTE",
  "TOTEM", "TRAFO", "TREND", "TRICK", "TROLL", "TROPF", "TROSS", "TRUHE",
  "TUMOR", "VATER", "VERSE", "VESPA", "VIDEO", "VILLA", "VIOLA", "VIREN",
  "VIRUS", "VLIES", "VOKAL", "VOTUM", "WAFFE", "WALZE", "WANGE", "WANZE",
  "WARZE", "WATTE", "WEDEL", "WEIDE", "WEISE", "WELLE", "WELPE", "WENDE",
  "WERFT", "WESEN", "WESTE", "WICHT", "WICKE", "WIEGE", "WIESE", "WINDE",
  "WIPPE", "WISCH", "WITWE", "WONNE", "WRACK", "WUNDE", "ZANGE", "ZEHEN",
  "ZEILE", "ZEUGE", "ZINKE", "ZINNE", "ZITAT", "ZUBER", "ZUNGE", "ZWIRN",
];

const EN: string[] = [
  "ABOUT", "ALARM", "ALIVE", "APPLE", "BEACH", "BERRY", "BLAME", "BLANK",
  "BLAST", "BLOOM", "BOARD", "BRAIN", "BRAVE", "BREAD", "BRICK", "BRING",
  "BROWN", "BRUSH", "CABLE", "CANDY", "CHAIR", "CHARM", "CHASE", "CHESS",
  "CLOCK", "CLOUD", "COAST", "CRANE", "CREAM", "CROWN", "DANCE", "DELAY",
  "DIARY", "DOZEN", "DREAM", "DRINK", "DRIVE", "EAGLE", "EARTH", "EMPTY",
  "EXTRA", "FAITH", "FANCY", "FIELD", "FLAME", "FLASH", "FLEET", "FLOAT",
  "FLOOR", "FRESH", "FRUIT", "GHOST", "GIANT", "GLASS", "GLOBE", "GRACE",
  "GRAIN", "GRAPE", "GRASS", "GREEN", "HAPPY", "HEART", "HONEY", "HORSE",
  "HOTEL", "HOUSE", "JUICE", "KNIFE", "LEMON", "LIGHT", "LUCKY", "MAGIC",
  "MANGO", "MONEY", "MOUSE", "MUSIC", "NIGHT", "NOISE", "OCEAN", "OLIVE",
  "ONION", "PAINT", "PANDA", "PAPER", "PEACH", "PEARL", "PENNY", "PIANO",
  "PILOT", "PIZZA", "PLANT", "PLATE", "POINT", "POUND", "POWER", "PRIDE",
  "PRIZE", "QUEEN", "QUICK", "QUIET", "RADIO", "RIVER", "ROBOT", "ROUND",
  "ROYAL", "SALAD", "SHARK", "SHEEP", "SHINE", "SHIRT", "SHORE", "SMILE",
  "SNAKE", "SOLAR", "SOUND", "SPACE", "SPARK", "SPICE", "SPORT", "STAGE",
  "STONE", "STORM", "STORY", "SUGAR", "SUNNY", "SWEET", "TABLE", "TIGER",
  "TOAST", "TOOTH", "TOWER", "TRAIN", "TREAT", "TRUCK", "TULIP", "VOICE",
  "WATER", "WHALE", "WHEAT", "WHEEL", "WITCH", "WORLD", "YACHT", "ZEBRA",
  // Expansion
  "ABOVE", "AGAIN", "AGENT", "ALONE", "ANGEL", "ANGER", "ANGLE", "ARGUE",
  "ARROW", "AUDIO", "AWARD", "AWARE", "BACON", "BADGE", "BAKER", "BASIC",
  "BASIN", "BEARD", "BEAST", "BEGIN", "BELLY", "BENCH", "BIRTH", "BLADE",
  "BLAZE", "BLIND", "BLOOD", "BOOST", "BOOTH", "BRAND", "BRASS", "BREAK",
  "BREED", "BROAD", "BROOK", "BROOM", "BUNCH", "CABIN", "CAMEL", "CANAL",
  "CARGO", "CATCH", "CEDAR", "CHAIN", "CHALK", "CHART", "CHEAP", "CHEEK",
  "CHEER", "CHEST", "CHIEF", "CHILD", "CHILL", "CHINA", "CHOIR", "CIVIC",
  "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB",
  "CLOTH", "COACH", "COCOA", "CORAL", "COUCH", "COUNT", "COURT", "COVER",
  "CRAFT", "CRASH", "CRAZY", "CREEK", "CRISP", "CROSS", "CROWD", "CURVE",
  "CYCLE", "DAILY", "DAIRY", "DAISY", "DEPTH", "DITCH", "DODGE", "DONOR",
  "DOUBT", "DOUGH", "DRAFT", "DRAIN", "DRAMA", "DRESS", "DRIFT", "DROWN",
  "DWARF", "EAGER", "EARLY", "EIGHT", "ELBOW", "ELDER", "ENEMY", "ENJOY",
  "ENTER", "ENTRY", "EQUAL", "ERROR", "EVENT", "EVERY", "EXACT", "EXILE",
  "EXIST", "FABLE", "FAINT", "FAIRY", "FAULT", "FAVOR", "FENCE", "FERRY",
  "FEVER", "FIBER", "FINAL", "FIRST", "FLASK", "FLESH", "FLOCK", "FLOUR",
  "FLUID", "FOCUS", "FORCE", "FORGE", "FRAME", "FRANK", "FRAUD", "FROWN",
  "FUDGE", "GAUGE", "GLARE", "GLIDE", "GLORY", "GLOVE", "GRADE", "GRANT",
  "GRAPH", "GREAT", "GREET", "GRIEF", "GRILL", "GRIND", "GROVE", "GUARD",
  "GUEST", "GUIDE", "GUILD", "HABIT", "HARSH", "HASTE", "HATCH", "HAVEN",
  "HAZEL", "HEAVY", "HEDGE", "HELLO", "HERON", "HINGE", "HOBBY", "HOLLY",
  "HONOR", "HOUND", "HUMAN", "HUMID", "HURRY", "IDEAL", "IGLOO", "IMAGE",
  "INDEX", "INNER", "INPUT", "IRONY", "IVORY", "JELLY", "JEWEL", "JOLLY",
  "JUDGE", "JUMBO", "KAYAK", "LABEL", "LABOR", "LANCE", "LAPSE", "LARGE",
  "LATCH", "LATER", "LAYER", "LEARN", "LEASE", "LEDGE", "LEVEL", "LEVER",
  "LILAC", "LIMIT", "LINEN", "LIVER", "LLAMA", "LOCAL", "LODGE", "LOGIC",
  "LOTUS", "LOYAL", "LUNAR", "LUNCH", "LYRIC", "MACRO", "MAJOR", "MAPLE",
  "MARCH", "MARSH", "MASON", "MATCH", "MAYOR", "MEDAL", "MELON", "MERCY",
  "MERIT", "METAL", "MICRO", "MIGHT", "MINOR", "MIXER", "MODEL", "MOIST",
  "MONTH", "MOTEL", "MOTTO", "MOUNT", "MOURN", "MOVIE", "MUMMY", "MURAL",
  "NAVAL", "NERVE", "NEVER", "NEWLY", "NICHE", "NIECE", "NINJA", "NOBLE",
  "NOMAD", "NORTH", "NOVEL", "NURSE", "NYLON", "OASIS", "OCCUR", "OFFER",
  "ONSET", "OPERA", "ORBIT", "ORGAN", "OUNCE", "OWNER", "OZONE", "PANEL",
  "PANIC", "PARTY", "PASTE", "PATCH", "PATIO", "PAUSE", "PEACE", "PEDAL",
  "PERCH", "PHONE", "PHOTO", "PIECE", "PINCH", "PITCH", "PIVOT", "PLAID",
  "PLAIN", "PLANK", "PLAZA", "PLUMP", "POLAR", "PORCH", "PRIME", "PRINT",
  "PRIOR", "PROOF", "PROSE", "PROUD", "PROVE", "PULSE", "PUPIL", "PUREE",
  "QUAIL", "QUART", "QUERY", "QUEST", "QUILT", "QUOTA", "QUOTE", "RAINY",
  "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "RAVEN", "REACH", "REACT",
  "REALM", "REBEL", "REFER", "RELAX", "RELAY", "REPLY", "RESET", "RHINO",
  "RHYME", "RIDGE", "RIFLE", "RINSE", "ROAST", "ROBIN", "ROCKY", "ROGUE",
  "ROUGH", "ROUTE", "RUGBY", "RULER", "RUMOR", "RURAL", "SALSA", "SANDY",
  "SAUCE", "SCALE", "SCARF", "SCENE", "SCENT", "SCOPE", "SCORE", "SCOUT",
  "SCRAP", "SCRUB", "SEDAN", "SENSE", "SEVEN", "SHADE", "SHAFT", "SHAKE",
  "SHALL", "SHAME", "SHAPE", "SHARE", "SHARP", "SHEAR", "SHEET", "SHELF",
  "SHELL", "SHIFT", "SHINY", "SHORT", "SHOUT", "SHOWN", "SHRUB", "SIGHT",
  "SILKY", "SILLY", "SIREN", "SIXTH", "SIXTY", "SKATE", "SKILL", "SKIRT",
  "SKULL", "SLANT", "SLATE", "SLEEP", "SLICE", "SLIDE", "SLOPE", "SMART",
  "SMASH", "SMELL", "SMOKE", "SNACK", "SNAIL", "SNEAK", "SNOWY", "SOLID",
  "SONIC", "SORRY", "SOUTH", "SPARE", "SPEAK", "SPEAR", "SPEED", "SPELL",
  "SPEND", "SPILL", "SPINE", "SPLIT", "SPOKE", "SPOON", "SQUAD", "STACK",
  "STAFF", "STAIN", "STAIR", "STAMP", "STAND", "STARK", "START", "STATE",
  "STEAK", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STICK", "STIFF",
  "STILL", "STING", "STOCK", "STOOL", "STORE", "STOVE", "STRAP", "STRAW",
  "STRIP", "STUDY", "STUFF", "STUMP", "STYLE", "SUPER", "SURGE", "SWAMP",
  "SWEAT", "SWEEP", "SWELL", "SWIFT", "SWING", "SWORD", "SYRUP", "TASTE",
  "TEACH", "TENOR", "TENTH", "THEME", "THICK", "THIEF", "THING", "THINK",
  "THORN", "THREE", "THROW", "THUMB", "TITLE", "TODAY", "TOKEN", "TOPIC",
  "TORCH", "TOTAL", "TOUCH", "TOUGH", "TOXIC", "TRACE", "TRACK", "TRADE",
  "TRAIL", "TRAIT", "TRASH", "TRIAL", "TRIBE", "TROOP", "TROUT", "TRULY",
  "TRUNK", "TRUST", "TRUTH", "TUTOR", "TWICE", "TWIST", "ULTRA", "UNCLE",
  "UNDER", "UNION", "UNITY", "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE",
  "USHER", "VAGUE", "VALID", "VALUE", "VALVE", "VAPOR", "VAULT", "VENOM",
  "VENUE", "VIGOR", "VINYL", "VISIT", "VISOR", "VITAL", "VIVID", "VOCAL",
  "VODKA", "VOTER", "WAGON", "WAIST", "WALTZ", "WASTE", "WATCH", "WEARY",
  "WEAVE", "WEDGE", "WEIRD", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE",
  "WHOSE", "WIDEN", "WIDOW", "WIDTH", "WINDY", "WIPER", "WOMAN", "WORRY",
  "WORSE", "WORST", "WORTH", "WOUND", "WOVEN", "WRECK", "WRIST", "WRONG",
  "YEARN", "YEAST", "YIELD", "YOUNG", "YOUTH", "ZESTY",
];

// Entdoppeln + defensiv auf exakt 5 Buchstaben (A-Z) filtern.
const clean = (words: string[]): string[] =>
  Array.from(new Set(words)).filter((word) => /^[A-Z]{5}$/.test(word));

export const WORDLE_WORDS: Record<WordleLanguage, string[]> = {
  de: clean(DE),
  en: clean(EN),
};
